//
//  IbanCountry.swift
//  VisionTest
//
//  Created by ali cihan on 29.01.2025.
//

import Foundation

enum IBANCountry: String, CaseIterable, Identifiable {
    case albania = "AL"
    case andorra = "AD"
    case austria = "AT"
    case azerbaijan = "AZ"
    case bahrain = "BH"
    case belarus = "BY"
    case belgium = "BE"
    case bosniaHerzegovina = "BA"
    case brazil = "BR"
    case bulgaria = "BG"
    case burundi = "BI"
    case costaRica = "CR"
    case croatia = "HR"
    case cyprus = "CY"
    case czechRepublic = "CZ"
    case denmark = "DK"
    case djibouti = "DJ"
    case dominicanRepublic = "DO"
    case eastTimor = "TL"
    case egypt = "EG"
    case elSalvador = "SV"
    case estonia = "EE"
    case falklandIslands = "FK"
    case faroeIslands = "FO"
    case finland = "FI"
    case france = "FR"
    case georgia = "GE"
    case germany = "DE"
    case gibraltar = "GI"
    case greece = "GR"
    case greenland = "GL"
    case guatemala = "GT"
    case hungary = "HU"
    case iceland = "IS"
    case iraq = "IQ"
    case ireland = "IE"
    case israel = "IL"
    case italy = "IT"
    case jordan = "JO"
    case kazakhstan = "KZ"
    case kosovo = "KS"
    case kuwait = "KW"
    case latvia = "LV"
    case lebanon = "LB"
    case libya = "LY"
    case liechtenstein = "LI"
    case lithuania = "LT"
    case luxembourg = "LU"
    case malta = "MT"
    case mauritania = "MR"
    case mauritius = "MU"
    case monaco = "MC"
    case moldova = "MD"
    case mongolia = "MN"
    case montenegro = "ME"
    case netherlands = "NL"
    case nicaragua = "NI"
    case northMacedonia = "MK"
    case norway = "NO"
    case oman = "OM"
    case pakistan = "PK"
    case palestinianTerritories = "PS"
    case poland = "PL"
    case portugal = "PT"
    case qatar = "QA"
    case romania = "RO"
    case russia = "RU"
    case saintLucia = "LC"
    case sanMarino = "SM"
    case saoTomeAndPrincipe = "ST"
    case saudiArabia = "SA"
    case serbia = "RS"
    case seychelles = "SC"
    case slovakia = "SK"
    case slovenia = "SI"
    case somalia = "SO"
    case spain = "ES"
    case sudan = "SD"
    case sweden = "SE"
    case switzerland = "CH"
    case tunisia = "TN"
    case turkey = "TR"
    case ukraine = "UA"
    case unitedArabEmirates = "AE"
    case unitedKingdom = "GB"
    case vaticanCity = "VA"
    case virginIslandsBritish = "VG"
    case yemen = "YE"

    var count: Int {
        switch self {
        case .albania: return 28
        case .andorra: return 24
        case .austria: return 20
        case .azerbaijan: return 28
        case .bahrain: return 22
        case .belarus: return 28
        case .belgium: return 16
        case .bosniaHerzegovina: return 20
        case .brazil: return 29
        case .bulgaria: return 22
        case .burundi: return 27
        case .costaRica: return 22
        case .croatia: return 21
        case .cyprus: return 28
        case .czechRepublic: return 24
        case .denmark: return 18
        case .djibouti: return 27
        case .dominicanRepublic: return 28
        case .eastTimor: return 23
        case .egypt: return 29
        case .elSalvador: return 28
        case .estonia: return 20
        case .falklandIslands: return 18
        case .faroeIslands: return 18
        case .finland: return 18
        case .france: return 27
        case .georgia: return 22
        case .germany: return 22
        case .gibraltar: return 23
        case .greece: return 27
        case .greenland: return 18
        case .guatemala: return 28
        case .hungary: return 28
        case .iceland: return 26
        case .iraq: return 23
        case .ireland: return 22
        case .israel: return 23
        case .italy: return 27
        case .jordan: return 30
        case .kazakhstan: return 20
        case .kosovo: return 20
        case .kuwait: return 30
        case .latvia: return 21
        case .lebanon: return 28
        case .libya: return 25
        case .liechtenstein: return 21
        case .lithuania: return 20
        case .luxembourg: return 20
        case .malta: return 31
        case .mauritania: return 27
        case .mauritius: return 30
        case .monaco: return 27
        case .moldova: return 24
        case .mongolia: return 20
        case .montenegro: return 22
        case .netherlands: return 18
        case .nicaragua: return 28
        case .northMacedonia: return 19
        case .norway: return 15
        case .oman: return 23
        case .pakistan: return 24
        case .palestinianTerritories: return 29
        case .poland: return 28
        case .portugal: return 25
        case .qatar: return 29
        case .romania: return 24
        case .russia: return 33
        case .saintLucia: return 32
        case .sanMarino: return 27
        case .saoTomeAndPrincipe: return 25
        case .saudiArabia: return 24
        case .serbia: return 22
        case .seychelles: return 31
        case .slovakia: return 24
        case .slovenia: return 19
        case .somalia: return 23
        case .spain: return 24
        case .sudan: return 18
        case .sweden: return 24
        case .switzerland: return 21
        case .tunisia: return 24
        case .turkey: return 26
        case .ukraine: return 29
        case .unitedArabEmirates: return 23
        case .unitedKingdom: return 22
        case .vaticanCity: return 22
        case .virginIslandsBritish: return 24
        case .yemen: return 30
        }
    }
    
    var id: String { rawValue }
}
